### ISSUE TITLE
Checkbox and showError on blur

### ISSUE THREAD

**Issue by JoostKiens** [kaliberjs/forms#14]
Is it possible to show a validation error of a checkbox on blur?

See the following test case:

```jsx
import { useBooleanFormField, useForm } from '@kaliber/forms'

function needsToBeChecked(x) {
  return x !== true && { id: 'needsToBeChecked' }
}

export function Form() {
  const { form: { fields }, submit } = useForm({
    initialValues: { tos: false },
    fields: { tos: needsToBeChecked },
    onSubmit: x => { console.log(x) },
  })

  return (
    <form onSubmit={submit}>
      <FormCheckbox label='I agree with the Terms of Service' field={fields.tos} />
      <button type='submit'>Submit</button>
    </form>
  )
}
function FormCheckbox({ label, field }) {
  const { name, state, eventHandlers } = useBooleanFormField(field)
  const { showError, error, value } = state
  console.log(showError, error)
  return (
    <>
      <div>
        <label htmlFor={name}>{label}</label>
        <input id={name} type='checkbox' checked={value || false} {...{ name }} {...eventHandlers} />
      </div>
      {showError && <p>{error.id}</p>}
    </>
  )
}

```

I would expect the error to be shown as soon as we uncheck the checkbox. However,`showError` is always `false` until we submit the form.

**Comment by EECOLOR** [comment]
I have added an example that shows this behavior. Not sure what causes the problem in your test case.

**Comment by JoostKiens** [comment]
Thanks for the example!

> Not sure what causes the problem in your test case.

After investigating a bit, I found out it seems to be an issue in Firefox & Safari. This is also the case with your example.
In Chrome it works as expected.

**Comment by EECOLOR** [comment]
Let me know if you find a workaround

**Comment by EECOLOR** [comment]
Seems we are not alone: https://github.com/react-hook-form/react-hook-form/issues/1079

**Comment by JoostKiens** [comment]
Looks like browser bugs. Reports going back to 2007 😳. 

Seems I'll just have to accept that this is the world we live in. Closing, thanks for your time 👍

https://bugs.webkit.org/show_bug.cgi?id=13724
https://bugzilla.mozilla.org/show_bug.cgi?id=756028

**Comment by EECOLOR** [comment]
If we feel this is really important we could write a custom `onBlur`.
